# Ex 1

In [1]:
import numpy as np

rna="AUCGGAGCAUUUUUUGCUCCGACGCAGCCUCAUGCUUUUUU"
def delta(seq,i,j):   
        if seq[i]+seq[j] == 'UA' or seq[i]+seq[j] == 'AU' or seq[i]+seq[j] == 'CG' or seq[i]+seq[j] == 'GC':
            return 1        # if any given pair is complementary to each other returns 1, otherwise returns 0
        else:
            return 0    
        
def nussinov(seq):
    '''function hould take an RNA sequence asargument and return the complete 
    dynaminc programming matrix'''
    n = len(seq)
    N = np.zeros((n, n), dtype = int) #initially fill matrix with zeros
    for pos in range(n-2):   
        #to fill in the score matrix N(i,j)
        i = 0
        j = pos + 2 
         # allowing for a minimal loop length of 1 base
        for z in range(n-2-pos):
            a = N[i+1][j-1] + delta(seq,i,j)
            b = max([N[i][k] + N[k+1][j] for k in range(i,j)])
            N[i][j] = max(a, b)
            i += 1
            j += 1   
            
    return N


nussinov(rna)

array([[ 0,  0,  0, ..., 14, 14, 14],
       [ 0,  0,  0, ..., 13, 13, 13],
       [ 0,  0,  0, ..., 13, 13, 13],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

# EX2

In [2]:
matched = []
n= len(rna) # rna sequence length
def backtracking(seq,N,i,j):
    '''returns the list of all matched base pairs'''
    if j-i > 1:
        if N[i][j] == N[i+1][j-1] + delta(seq,i,j):
            #if any given pair is complementary to each other then add in mathed base pair list
            if delta(seq,i,j) == 1:
                matched.append((i,j))
                backtracking(seq,N,i+1,j-1)
                # otherwise just continue
            else:
                backtracking(seq,N,i+1,j-1)   
        else:
            for k in range(i,j):    
                if N[i][j] == N[i][k] + N[k+1][j]:
                    #need to retrieve the list of paired complementary bases andjoin them.
                    backtracking(seq,N,i,k)
                    backtracking(seq,N,k+1,j)
                    break            
    return matched
    
backtracking(rna,nussinov(rna),0,n-1)    

[(0, 40),
 (2, 20),
 (3, 19),
 (4, 18),
 (5, 17),
 (6, 16),
 (7, 15),
 (8, 14),
 (21, 38),
 (23, 34),
 (24, 33),
 (25, 32),
 (26, 28),
 (29, 31)]

# Ex 3

In [3]:
def display(seq,match):
    '''To display the resulting basepair use parentheses to produce an output'''
    output = [ "." for i in range(len(seq))]
    for pair in match:
        output[pair[0]] = "("
        output[pair[1]] = ")" 
    return "".join(output)

base_pairs = display(rna,backtracking(rna,nussinov(rna),0,n-1))
print('',rna,'\n',base_pairs,'\n','\n','There are ',str(base_pairs.count('(')),' base pairs')

 AUCGGAGCAUUUUUUGCUCCGACGCAGCCUCAUGCUUUUUU 
 (.(((((((.....)))))))(.((((.)(.))))...).) 
 
 There are  14  base pairs


# EX4

In [4]:
def nussinov_modified(seq,h):
    '''Modify the algorithm so that a parameter h,indicating the minimumal lowed loop length'''
    n = len(seq)
    N = np.zeros((n, n), dtype = int) #initially fill matrix with zeros
    for ind in range(n-h+1):   #to fill in the score matrix N(i,j)
        i = 0
        j = ind + h+1    
        for z in range(n-1-ind-h):
            a = N[i+1][j-1] + delta(seq,i,j)
            b = max([N[i][k] + N[k+1][j] for k in range(i,j)])
            N[i][j] = max(a, b)
            i += 1
            j += 1   
            
    return N

print(nussinov_modified(rna,0))



[[ 0  1  1 ... 14 14 14]
 [ 0  0  0 ... 13 13 13]
 [ 0  0  0 ... 13 13 13]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [5]:
print(nussinov_modified(rna,1))

[[ 0  0  0 ... 14 14 14]
 [ 0  0  0 ... 13 13 13]
 [ 0  0  0 ... 13 13 13]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [6]:
print(nussinov_modified(rna,2))

[[ 0  0  0 ... 13 13 13]
 [ 0  0  0 ... 12 12 12]
 [ 0  0  0 ... 12 12 12]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
